# .github/actions/compose-email/action.yml
name: 'Compose Mail'
description: 'Compose an email based on the workflow message'
inputs:
  workflow_message:
    description: 'The message from the workflow'
    required: true
outputs:
  emailBody:
    description: 'The composed email body'
    value: ${{ steps.compose-mail.outputs.emailBody }}
runs:
  using: 'composite'
  steps:
    - name: 'Compose Email'
      id: compose-mail
      shell: pwsh
      run: |
        actions/compose-mail/ComposeEmail.ps1 -Message "${{ inputs.workflow_message }}"
