# .github/actions/compose-email/action.yml
name: 'Compose Mail'
description: 'Compose an email based on the workflow message'
inputs:
  workflowMessage:
    description: 'Message to include in the email'
    required: true
  workflowRunName:
    description: 'The workflow run name'
    required: false
  workflowRunId:
    description: 'The workflow run ID'
    required: false

outputs:
  emailBody:
    description: 'The composed email body'
    value: ${{ steps.compose_mail.outputs.emailBody }}
runs:
  using: 'composite'
  steps:
    - name: 'Compose Email'
      id: compose_mail
      shell: pwsh
      run: |
        try { ${{ github.action_path }}/ComposeEmail.ps1 -Message "${{ inputs.workflowMessage }}" -RunName "${{ inputs.workflowRunName }}" -RunId "${{ inputs.workflowRunId }}" } catch { Write-Host "::Error::Unexpected error when running action ($($_.Exception.Message))"; exit 1 }
