# .github/actions/compose-email/action.yml
name: 'Compose Mail'
description: 'Compose an email based on the workflow message'
inputs:
  workflow_message:
    description: 'The message from the workflow'
    required: true
  workflow_run_name:
    description: 'The message from the workflow'
    required: true
  workflow_run_id:
    description: 'The message from the workflow'
    required: true
outputs:
  emailBody:
    description: 'The composed email body'
    value: ${{ steps.compose-mail.outputs.emailBody }}
runs:
  using: 'composite'
  steps:
    - name: 'Compose Email'
      id: compose-mail
      shell: pwsh
      run: |
        try { ${{ github.action_path }}/ComposeEmail.ps1 -Message "${{ inputs.workflow_message }}" -RunName "${{ inputs.workflow_run_name }}" -RunId "${{ inputs.workflow_run_id }}" } catch { Write-Host "::Error::Unexpected error when running action ($($_.Exception.Message))"; exit 1 }
