name: 'Compose Mail'
description: 'Compose an email based on the workflow message'
inputs:
  workflow_message:
    description: 'The message from the workflow'
    required: true
  workflow_run_name:  # Ensure this input is defined
    description: 'The name of the workflow run'
    required: false
  workflow_run_id:  # Ensure this input is defined
    description: 'The ID of the workflow run'
    required: false
outputs:
  email_body:
    description: 'The composed email body'
    value: ${{ steps.compose-mail.outputs.email_body }}
  workflow_run_name:
    description: 'The name of the workflow run'
    value: ${{ steps.compose-mail.outputs.workflow_run_name }}
  workflow_run_id:
    description: 'The ID of the workflow run'
    value: ${{ steps.compose-mail.outputs.workflow_run_id }}
runs:
  using: 'composite'
  steps:
    - name: 'Compose Email'
      id: compose-mail
      shell: pwsh
      run: |
        ${{ github.action_path }}/actions/compose-mail/ComposeEmail.ps1 -Message "${{ inputs.workflow_message }}" -RunName "${{ inputs.workflow_run_name }}" -RunId "${{ inputs.workflow_run_id }}"
